name: Build and Deploy

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions-rust-lang/setup-rust-toolchain@main
        with:
          toolchain: 1.74.0

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4
          bundler-cache: true
          working-directory: ruby-wasm

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: 21
          cache: pnpm

      - name: Cache ruby.wasm artefacts
        id: cache-ruby-wasm
        uses: actions/cache@v4
        with:
          path: |
            ruby-wasm/build
            ruby-wasm/rubies
          key: ${{ runner.os }}-v1-ruby-wasm
          save-always: true

      - name: Cache compiled ruby.wasm module
        id: cache-ruby-wasm-module
        uses: actions/cache@v4
        with:
          path: |
            public/ruby.wasm
            public/ruby.wasm.hash
          key: ${{ runner.os }}-v1-${{ hashFiles('ruby-wasm/Gemfile.lock') }}-ruby-wasm-module

      - name: Install wasi-vfs
        if: steps.cache-ruby-wasm-module.outputs.cache-hit != 'true'
        run: |
          curl -LO "https://github.com/kateinoigakukun/wasi-vfs/releases/download/v0.5.5/wasi-vfs-cli-x86_64-unknown-linux-gnu.zip"
          unzip wasi-vfs-cli-x86_64-unknown-linux-gnu.zip
          sudo mv wasi-vfs /usr/local/bin/wasi-vfs
          wasi-vfs --version

      - name: Build ruby.wasm
        if: steps.cache-ruby-wasm-module.outputs.cache-hit != 'true'
        run: pnpm run build:wasm

      - name: Install dependencies
        run: pnpm install

      - name: Build web app
        run: pnpm run build

      - name: Setup flyctl
        if: github.ref == 'refs/heads/master' || github.event_name == 'workflow_dispatch'
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Fly.io
        if: github.ref == 'refs/heads/master' || github.event_name == 'workflow_dispatch'
        run: flyctl deploy --local-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
